/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import logica.VueloLogica;
import logica.TicketLogica;
import modelo.Vuelo;
import modelo.Ticket;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author chris
 */
public class FrmCompraTiquetes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCompraTiquetes.class.getName());
    private final VueloLogica vueloLogica = new VueloLogica();
    private final TicketLogica ticketLogica = new TicketLogica();
    private Vuelo vueloSeleccionado = null;

    /**
     * Creates new form FrmCompraTiquetes
     */
    public FrmCompraTiquetes() {
        initComponents();
        setLocationRelativeTo(null);
        cargarComboVuelos();
    }
    
    private void cargarComboVuelos(){
        cmbVuelo.removeAllItems();
        List<Vuelo> vuelos= vueloLogica.listarVuelosProgramados();
        for (Vuelo v : vuelos) {
            cmbVuelo.addItem(v);
        }
    }
    private void mostrarInfoVuelo(){
        if (vueloSeleccionado==null) {
            lblInfoAvion.setText("-");
            lblInfoPiloto.setText("-");
            lblInfoDestino.setText("-");
            lblInfoFechaSalida.setText("-");
            lblInfoAsientos.setText("-");
            return;
        }
        
        lblInfoAvion.setText(vueloSeleccionado.getAvion().getModelo()+" ("
            +vueloSeleccionado.getAvion().getAerolinea().getNombre()+")");
        lblInfoPiloto.setText(vueloSeleccionado.getPiloto().getNombre()+" "
            +vueloSeleccionado.getPiloto().getApellidos());
         lblInfoDestino.setText(vueloSeleccionado.getPaisDestino() + ", "
            + vueloSeleccionado.getCiudadDestino());
         lblInfoFechaSalida.setText(vueloSeleccionado.getFechaHoraSalida().toString());
         
         int disponibles = ticketLogica.asientosDisponibles(vueloSeleccionado);
         lblInfoAsientos.setText("Asientos disponibles: "+disponibles);
         
    }
    private void cargarTablaTiquetesDelVuelo(){
        DefaultTableModel modelo = (DefaultTableModel) tblTiquetesVuelo.getModel();
        modelo.setRowCount(0);
        if (vueloSeleccionado == null) {
            return;
        }
        List<Ticket> todosLosTickets = ticketLogica.listarTickets();
        for (Ticket t : todosLosTickets) {
            if (t.getVuelo().getIdVuelo() == vueloSeleccionado.getIdVuelo()) {
                Object[] fila= {
                    t.getIdTicket(),
                    t.getPasajero().getNombreCompleto(),
                    t.getVuelo().getFechaHoraSalida(),
                    t.getNumeroAsiento(),
                    t.getVuelo().getPaisDestino(),
                    t.getVuelo().getCiudadDestino()
                };
                modelo.addRow(fila);
            }
        }
    }
    private void limpiarFormulario(){
        txtCedula.setText("");
        txtNombreCompleto.setText("");
        txtPasaporte.setText("");
        dchVencePasaporte.setDate(null);
        txtNumAsiento.setText("");
    }
    private LocalDate convertirALocalDate(Date fecha){
        if (fecha ==null) {
            return null;
        }
        return fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    /*

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiquetesVuelo = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        pnlInfoVuelosDisponibles = new javax.swing.JPanel();
        cmbVuelo = new javax.swing.JComboBox<>();
        lblCapacidad2 = new javax.swing.JLabel();
        lblTituloInfoVuelosDis = new javax.swing.JLabel();
        lblInfoAvion = new javax.swing.JLabel();
        lblInfoPiloto = new javax.swing.JLabel();
        lblInfoDestino = new javax.swing.JLabel();
        lblInfoFechaSalida = new javax.swing.JLabel();
        lblInfoAsientos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        txtPasaporte = new javax.swing.JTextField();
        lblPasaporte = new javax.swing.JLabel();
        dchVencePasaporte = new com.toedter.calendar.JDateChooser();
        lblVencPasaporte = new javax.swing.JLabel();
        lblnumLicencia1 = new javax.swing.JLabel();
        txtNumAsiento = new javax.swing.JTextField();
        lblTituloInfoPasajeros = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnComprarTiquete = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTiquetesVuelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pasajeros", "Fecha/Hora/Salida", "Numero Asiento", "Pais Destino", "Ciudad Destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTiquetesVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiquetesVueloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTiquetesVuelo);

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Compra de Tiquetes");

        cmbVuelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbVuelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVueloItemStateChanged(evt);
            }
        });

        lblCapacidad2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCapacidad2.setText("Vuelos:");

        lblTituloInfoVuelosDis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloInfoVuelosDis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloInfoVuelosDis.setText("Vuelos Disponibles");

        javax.swing.GroupLayout pnlInfoVuelosDisponiblesLayout = new javax.swing.GroupLayout(pnlInfoVuelosDisponibles);
        pnlInfoVuelosDisponibles.setLayout(pnlInfoVuelosDisponiblesLayout);
        pnlInfoVuelosDisponiblesLayout.setHorizontalGroup(
            pnlInfoVuelosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoVuelosDisponiblesLayout.createSequentialGroup()
                .addGroup(pnlInfoVuelosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoVuelosDisponiblesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblCapacidad2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoVuelosDisponiblesLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(pnlInfoVuelosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInfoAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlInfoVuelosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblInfoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                .addComponent(lblInfoPiloto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                .addComponent(lblInfoAvion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblInfoFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
            .addComponent(lblTituloInfoVuelosDis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlInfoVuelosDisponiblesLayout.setVerticalGroup(
            pnlInfoVuelosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoVuelosDisponiblesLayout.createSequentialGroup()
                .addComponent(lblTituloInfoVuelosDis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoVuelosDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCapacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        lblCedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCedula.setText("Cedula:");

        lblNombreCompleto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreCompleto.setText("NombreCompleto:");

        lblPasaporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPasaporte.setText("Pasaporte:");

        lblVencPasaporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVencPasaporte.setText("Venc.Pasaporte:");

        lblnumLicencia1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnumLicencia1.setText("NumeroAsiento:");

        lblTituloInfoPasajeros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloInfoPasajeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloInfoPasajeros.setText("Informacion Pasajero:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTituloInfoPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPasaporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVencPasaporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnumLicencia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombreCompleto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPasaporte, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCedula)
                        .addComponent(dchVencePasaporte, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addComponent(txtNumAsiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTituloInfoPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCompleto)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasaporte)
                    .addComponent(txtPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVencPasaporte)
                    .addComponent(dchVencePasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumLicencia1)
                    .addComponent(txtNumAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnComprarTiquete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComprarTiquete.setText("Comprar Tiquete");
        btnComprarTiquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarTiqueteActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar Formulario");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(btnComprarTiquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnComprarTiquete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(pnlInfoVuelosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInfoVuelosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 195, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTiquetesVueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiquetesVueloMouseClicked

    }//GEN-LAST:event_tblTiquetesVueloMouseClicked

    private void btnComprarTiqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarTiqueteActionPerformed
        if (vueloSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vuelo primero. ",
                    "Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            ticketLogica.comprarTicket(
                    txtCedula.getText(),
                    txtNombreCompleto.getText(),
                    txtPasaporte.getText(),
                    convertirALocalDate(dchVencePasaporte.getDate()),
                    vueloSeleccionado,
                    txtNumAsiento.getText()
            );
            JOptionPane.showMessageDialog(this, "Tiquete comprado con exito. ");
            limpiarFormulario();
            mostrarInfoVuelo();
            cargarTablaTiquetesDelVuelo();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnComprarTiqueteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void cmbVueloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVueloItemStateChanged
        if (evt.getStateChange()!=ItemEvent.SELECTED) {
            return;
        }
        vueloSeleccionado = (Vuelo) cmbVuelo.getSelectedItem();
        mostrarInfoVuelo();
        cargarTablaTiquetesDelVuelo();
    }//GEN-LAST:event_cmbVueloItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCompraTiquetes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarTiquete;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Vuelo> cmbVuelo;
    private com.toedter.calendar.JDateChooser dchVencePasaporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCapacidad2;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblInfoAsientos;
    private javax.swing.JLabel lblInfoAvion;
    private javax.swing.JLabel lblInfoDestino;
    private javax.swing.JLabel lblInfoFechaSalida;
    private javax.swing.JLabel lblInfoPiloto;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblPasaporte;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloInfoPasajeros;
    private javax.swing.JLabel lblTituloInfoVuelosDis;
    private javax.swing.JLabel lblVencPasaporte;
    private javax.swing.JLabel lblnumLicencia1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInfoVuelosDisponibles;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JTable tblTiquetesVuelo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNumAsiento;
    private javax.swing.JTextField txtPasaporte;
    // End of variables declaration//GEN-END:variables
}
