/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.CardLayout;

/**
 *
 * @author chris
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    private final CardLayout cardLayout = new CardLayout();
    private final PnlAviones pnlAviones = new PnlAviones();
    private final PnlPilotos pnlPilotos = new PnlPilotos();
    private final PnlVuelos pnlVuelos = new PnlVuelos();
    private final PnlCompraTiquetes pnlCompraTiquetes = new PnlCompraTiquetes();
    private final PnlListadoTiquetes pnlListadoTiquetes = new PnlListadoTiquetes();

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        configurarPanelContenido();
        pack();
        setLocationRelativeTo(null);
    }
    
    private void configurarPanelContenido() {
        pnlContenido.setLayout(cardLayout);

        pnlContenido.add(pnlAviones, "AVIONES");
        pnlContenido.add(pnlPilotos, "PILOTOS");
        pnlContenido.add(pnlVuelos, "VUELOS");
        pnlContenido.add(pnlCompraTiquetes, "COMPRA");
        pnlContenido.add(pnlListadoTiquetes, "LISTADO");

        cardLayout.show(pnlContenido, "AVIONES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnMenuAviones = new javax.swing.JButton();
        btnMenuPilotos = new javax.swing.JButton();
        btnMenuVuelos = new javax.swing.JButton();
        btnMenuCompra = new javax.swing.JButton();
        btnMenuListado = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setLayout(new java.awt.BorderLayout());

        pnlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 649));
        pnlMenu.setLayout(new javax.swing.BoxLayout(pnlMenu, javax.swing.BoxLayout.Y_AXIS));

        btnMenuAviones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuAviones.setText("AVIONES");
        btnMenuAviones.setAlignmentX(0.5F);
        btnMenuAviones.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));
        btnMenuAviones.setMaximumSize(new java.awt.Dimension(180, 50));
        btnMenuAviones.setPreferredSize(new java.awt.Dimension(180, 50));
        btnMenuAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAvionesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMenuAviones);

        btnMenuPilotos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuPilotos.setText("PILOTOS");
        btnMenuPilotos.setAlignmentX(0.5F);
        btnMenuPilotos.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));
        btnMenuPilotos.setMaximumSize(new java.awt.Dimension(180, 50));
        btnMenuPilotos.setPreferredSize(new java.awt.Dimension(180, 50));
        btnMenuPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPilotosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMenuPilotos);

        btnMenuVuelos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuVuelos.setText("VUELOS");
        btnMenuVuelos.setAlignmentX(0.5F);
        btnMenuVuelos.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));
        btnMenuVuelos.setMaximumSize(new java.awt.Dimension(180, 50));
        btnMenuVuelos.setPreferredSize(new java.awt.Dimension(180, 50));
        btnMenuVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuVuelosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMenuVuelos);

        btnMenuCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuCompra.setText("COMPRA TIQUETES");
        btnMenuCompra.setAlignmentX(0.5F);
        btnMenuCompra.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));
        btnMenuCompra.setMaximumSize(new java.awt.Dimension(180, 50));
        btnMenuCompra.setPreferredSize(new java.awt.Dimension(180, 50));
        btnMenuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCompraActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMenuCompra);

        btnMenuListado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuListado.setText("LISTADO TIQUETES");
        btnMenuListado.setAlignmentX(0.5F);
        btnMenuListado.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 8, 0));
        btnMenuListado.setMaximumSize(new java.awt.Dimension(180, 50));
        btnMenuListado.setPreferredSize(new java.awt.Dimension(180, 50));
        btnMenuListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuListadoActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMenuListado);

        pnlFondo.add(pnlMenu, java.awt.BorderLayout.LINE_START);

        pnlContenido.setLayout(new java.awt.CardLayout());
        pnlFondo.add(pnlContenido, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAvionesActionPerformed
        pnlAviones.actualizarDatos();
        cardLayout.show(pnlContenido, "AVIONES");
    }//GEN-LAST:event_btnMenuAvionesActionPerformed

    private void btnMenuPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPilotosActionPerformed
        pnlPilotos.actualizarDatos();
        cardLayout.show(pnlContenido, "PILOTOS");
    }//GEN-LAST:event_btnMenuPilotosActionPerformed

    private void btnMenuVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuVuelosActionPerformed
        pnlVuelos.actualizarDatos();
        cardLayout.show(pnlContenido, "VUELOS");
    }//GEN-LAST:event_btnMenuVuelosActionPerformed

    private void btnMenuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCompraActionPerformed
        pnlCompraTiquetes.actualizarDatos();
        cardLayout.show(pnlContenido, "COMPRA");
    }//GEN-LAST:event_btnMenuCompraActionPerformed

    private void btnMenuListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuListadoActionPerformed
        pnlListadoTiquetes.actualizarDatos();
        cardLayout.show(pnlContenido, "LISTADO");
    }//GEN-LAST:event_btnMenuListadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuAviones;
    private javax.swing.JButton btnMenuCompra;
    private javax.swing.JButton btnMenuListado;
    private javax.swing.JButton btnMenuPilotos;
    private javax.swing.JButton btnMenuVuelos;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
