/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import iconos.GeneradorIconos;
import logica.*;
import modelo.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author chris
 */
public class PnlVuelos extends javax.swing.JPanel {
 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PnlVuelos.class.getName());
    private final VueloLogica vueloLogica = new VueloLogica();
    private final PilotoLogica pilotoLogica = new PilotoLogica();
    private final AvionLogica avionLogica = new AvionLogica();
    private Vuelo vueloSeleccionado = null;
    private final DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    /**
     * Creates new form PnlVuelos
     */
    public PnlVuelos() {
        initComponents();
        Config_jspinnerHora();
        cargarVuelos();
        cargarPilotos();
        cargarTablaVuelos();
        actualizarDatos();
    }

    private void Config_jspinnerHora() {
        SpinnerDateModel modeloHora = new SpinnerDateModel();
        spnHoraSalida.setModel(modeloHora);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spnHoraSalida, "HH:mm");
        spnHoraSalida.setEditor(editor);
    }

    private void cargarVuelos() {
        cmbAvion.removeAllItems();
        List<Avion> aviones = avionLogica.listarAvionesActivos();
        for (Avion a : aviones) {
            cmbAvion.addItem(a);
        }
    }

    private void cargarPilotos() {
        cmbPiloto.removeAllItems();
        List<Piloto> pilotos = pilotoLogica.listarPilotosConLicenciaVigente();
        for (Piloto p : pilotos) {
            cmbPiloto.addItem(p);
        }
    }

    private void cargarTablaVuelos() {
        DefaultTableModel modelo = (DefaultTableModel) tblVuelos.getModel();
        modelo.setRowCount(0);

        List<Vuelo> vuelos = vueloLogica.listarVuelos();
        for (Vuelo v : vuelos) {
            Object[] fila = {
                v.getIdVuelo(),
                v.getAvion().getAerolinea().getNombre(),
                v.getAvion().getModelo(),
                v.getPiloto().getNombre() + " " + v.getPiloto().getApellidos(),
                v.getPaisDestino(),
                v.getCiudadDestino(),
                v.getFechaHoraSalida().format(formatoFecha),
                v.getEstado()
            };
            modelo.addRow(fila);
        }
    }

    private void limpiarFormulario() {
        txtPaisDestino.setText("");
        txtCiudadDestino.setText("");
        dchFechaSalida.setDate(null);
        spnHoraSalida.setValue(new Date());
    }

    private LocalDateTime obtenerFechaHoraSeleccionada() {
        Date fechaSeleccionada = dchFechaSalida.getDate();
        if (fechaSeleccionada == null) {
            return null;
        }

        LocalDate fecha = fechaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();
        Date horaSeleccionada = (Date) spnHoraSalida.getValue();
        LocalTime hora = horaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault()).toLocalTime();
        return LocalDateTime.of(fecha, hora);
    }
    public void actualizarDatos() {
        cargarVuelos();
        cargarPilotos();
        cargarTablaVuelos();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Image img = (java.awt.Image) getClientProperty("background_image");
                if (img != null) {
                    // Esto calcula las dimensiones para centrar la imagen sin deformarla
                    int imgWidth = img.getWidth(this);
                    int imgHeight = img.getHeight(this);
                    int x = (getWidth() - imgWidth) / 2;
                    int y = (getHeight() - imgHeight) / 2;
                    g.drawImage(img, x, y, this);
                }
            }
        }
        ;
        pnlFondo.putClientProperty("background_image", new javax.swing.ImageIcon(getClass().getResource("/imagenes/AvionFondo.png")).getImage());

        pnlListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        pnlInsertar = new javax.swing.JPanel();
        cmbAvion = new javax.swing.JComboBox<>();
        lblPaisDestino = new javax.swing.JLabel();
        txtPaisDestino = new javax.swing.JTextField();
        lblCiudadDestino = new javax.swing.JLabel();
        txtCiudadDestino = new javax.swing.JTextField();
        cmbPiloto = new javax.swing.JComboBox<>();
        lblPiloto = new javax.swing.JLabel();
        lblAvion = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        dchFechaSalida = new com.toedter.calendar.JDateChooser();
        lblHoraSalida = new javax.swing.JLabel();
        spnHoraSalida = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        pnlBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton("Registrar Nuevo", iconos.GeneradorIconos.getAccionRegistrar())
        ;
        btnCancelarVuelo = new javax.swing.JButton("Cancelar Vuelo", iconos.GeneradorIconos.getAccionCancelar())
        ;
        btnFinalizarVuelo = new javax.swing.JButton("Finalizar Vuelo", iconos.GeneradorIconos.getAccionFinalizar())
        ;
        btnLimpiar = new javax.swing.JButton("Limpiar Formulario", iconos.GeneradorIconos.getAccionLimpiar())
        ;
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(947, 695));
        setPreferredSize(new java.awt.Dimension(947, 695));

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        pnlListar.setBackground(new java.awt.Color(255, 255, 255));
        pnlListar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABLA GENERAL DE VUELOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(27, 42, 74))); // NOI18N
        pnlListar.setOpaque(false);

        jScrollPane1.setOpaque(false);

        tblVuelos.setBackground(new java.awt.Color(255, 255, 255));
        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Aerolinea", "Avion", "Piloto", "Pais Destino", "Ciudad Destino", "Fecha/Hora Salida", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVuelos.setOpaque(false);
        tblVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVuelos);

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(27, 42, 74));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ASIGNAR VUELOS");
        lblTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pnlInsertar.setBackground(new java.awt.Color(255, 255, 255));
        pnlInsertar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ITENERARIO VUELOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(27, 42, 74))); // NOI18N
        pnlInsertar.setOpaque(false);
        pnlInsertar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAvion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbAvion.setForeground(java.awt.Color.black);
        pnlInsertar.add(cmbAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 37, 291, -1));

        lblPaisDestino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaisDestino.setText("Pais Destino:");
        pnlInsertar.add(lblPaisDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 119, 109, -1));

        txtPaisDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPaisDestino.setForeground(new java.awt.Color(27, 42, 74));
        pnlInsertar.add(txtPaisDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 119, 293, -1));

        lblCiudadDestino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCiudadDestino.setText("Ciudad Destino:");
        pnlInsertar.add(lblCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 153, 109, -1));

        txtCiudadDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCiudadDestino.setForeground(new java.awt.Color(27, 42, 74));
        pnlInsertar.add(txtCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 153, 293, -1));

        cmbPiloto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbPiloto.setForeground(java.awt.Color.black);
        pnlInsertar.add(cmbPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 75, 293, -1));

        lblPiloto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPiloto.setText("Piloto:");
        pnlInsertar.add(lblPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 78, 74, -1));

        lblAvion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAvion.setText("Avion:");
        pnlInsertar.add(lblAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 40, 78, -1));

        lblFechaSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaSalida.setText("Fecha de Salida:");
        pnlInsertar.add(lblFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 187, -1, -1));

        dchFechaSalida.setForeground(new java.awt.Color(27, 42, 74));
        pnlInsertar.add(dchFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 187, 293, -1));

        lblHoraSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoraSalida.setText("Hora de Salida:");
        pnlInsertar.add(lblHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 229, 109, -1));
        pnlInsertar.add(spnHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 227, 293, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 153));
        pnlInsertar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 153));
        pnlInsertar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 10));

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERACIONES DE VUELO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(27, 42, 74))); // NOI18N
        pnlBotones.setOpaque(false);
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(46, 74, 125));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Registrar Nuevo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 283, 47));

        btnCancelarVuelo.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarVuelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarVuelo.setText("Cancelar Vuelo");
        btnCancelarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVueloActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 283, 43));

        btnFinalizarVuelo.setBackground(new java.awt.Color(0, 102, 0));
        btnFinalizarVuelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFinalizarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarVuelo.setText("Finalizar Vuelo");
        btnFinalizarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVueloActionPerformed(evt);
            }
        });
        pnlBotones.add(btnFinalizarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 283, 45));

        btnLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar Formulario");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 283, 41));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 153));
        pnlBotones.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 153));
        pnlBotones.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 90, 10));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(pnlInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(pnlInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVuelosMouseClicked
        int filaSeleccionada = tblVuelos.getSelectedRow();
        if (filaSeleccionada == -1) {
            return;
        }
        List<Vuelo> vuelos = vueloLogica.listarVuelos();
        vueloSeleccionado = vuelos.get(filaSeleccionada);

    }//GEN-LAST:event_tblVuelosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            try {
                spnHoraSalida.commitEdit();
            } catch (java.text.ParseException ex) {
                JOptionPane.showMessageDialog(this, "La hora ingresada no es valida.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Vuelo vuelo = new Vuelo();
            vuelo.setAvion((Avion) cmbAvion.getSelectedItem());
            vuelo.setPiloto((Piloto) cmbPiloto.getSelectedItem());
            vuelo.setPaisDestino(txtPaisDestino.getText());
            vuelo.setCiudadDestino(txtCiudadDestino.getText());
            vuelo.setFechaHoraSalida(obtenerFechaHoraSeleccionada());
            vuelo.setEstado("Programado");

            vueloLogica.registrarVuelo(vuelo);
            JOptionPane.showMessageDialog(this, "Vuelo registrado con exito. ");
            limpiarFormulario();
            cargarTablaVuelos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVueloActionPerformed
        if (vueloSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vuelo de la tabla primero. ",
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            vueloLogica.cancelarVuelo(vueloSeleccionado.getIdVuelo());
            JOptionPane.showMessageDialog(this, "Vuelo cancelado. ");
            vueloSeleccionado = null;
            tblVuelos.clearSelection();
            cargarTablaVuelos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarVueloActionPerformed

    private void btnFinalizarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVueloActionPerformed
        if (vueloSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vuelo de la tabla. ",
                "Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            vueloLogica.finalizarVuelo(vueloSeleccionado.getIdVuelo());
            JOptionPane.showMessageDialog(this, "Vuelo finalizado. ");
            vueloSeleccionado = null;
            tblVuelos.clearSelection();
            cargarTablaVuelos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFinalizarVueloActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
        vueloSeleccionado = null;
        tblVuelos.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarVuelo;
    private javax.swing.JButton btnFinalizarVuelo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Avion> cmbAvion;
    private javax.swing.JComboBox<Piloto> cmbPiloto;
    private com.toedter.calendar.JDateChooser dchFechaSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAvion;
    private javax.swing.JLabel lblCiudadDestino;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblPaisDestino;
    private javax.swing.JLabel lblPiloto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInsertar;
    private javax.swing.JPanel pnlListar;
    private javax.swing.JSpinner spnHoraSalida;
    private javax.swing.JTable tblVuelos;
    private javax.swing.JTextField txtCiudadDestino;
    private javax.swing.JTextField txtPaisDestino;
    // End of variables declaration//GEN-END:variables
}
