/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import logica.*;
import modelo.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author chris
 */
public class PnlVuelos extends javax.swing.JPanel {
 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PnlVuelos.class.getName());
    private final VueloLogica vueloLogica = new VueloLogica();
    private final PilotoLogica pilotoLogica = new PilotoLogica();
    private final AvionLogica avionLogica = new AvionLogica();
    private Vuelo vueloSeleccionado = null;
    private final DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    /**
     * Creates new form PnlVuelos
     */
    public PnlVuelos() {
        initComponents();
        Config_jspinnerHora();
        cargarVuelos();
        cargarPilotos();
        cargarTablaVuelos();
        actualizarDatos();
    }

    private void Config_jspinnerHora() {
        SpinnerDateModel modeloHora = new SpinnerDateModel();
        spnHoraSalida.setModel(modeloHora);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spnHoraSalida, "HH:mm");
        spnHoraSalida.setEditor(editor);
    }

    private void cargarVuelos() {
        cmbAvion.removeAllItems();
        List<Avion> aviones = avionLogica.listarAvionesActivos();
        for (Avion a : aviones) {
            cmbAvion.addItem(a);
        }
    }

    private void cargarPilotos() {
        cmbPiloto.removeAllItems();
        List<Piloto> pilotos = pilotoLogica.listarPilotosConLicenciaVigente();
        for (Piloto p : pilotos) {
            cmbPiloto.addItem(p);
        }
    }

    private void cargarTablaVuelos() {
        DefaultTableModel modelo = (DefaultTableModel) tblVuelos.getModel();
        modelo.setRowCount(0);

        List<Vuelo> vuelos = vueloLogica.listarVuelos();
        for (Vuelo v : vuelos) {
            Object[] fila = {
                v.getIdVuelo(),
                v.getAvion().getAerolinea().getNombre(),
                v.getAvion().getModelo(),
                v.getPiloto().getNombre() + " " + v.getPiloto().getApellidos(),
                v.getPaisDestino(),
                v.getCiudadDestino(),
                v.getFechaHoraSalida().format(formatoFecha),
                v.getEstado()
            };
            modelo.addRow(fila);
        }
    }

    private void limpiarFormulario() {
        txtPaisDestino.setText("");
        txtCiudadDestino.setText("");
        dchFechaSalida.setDate(null);
        spnHoraSalida.setValue(new Date());
    }

    private LocalDateTime obtenerFechaHoraSeleccionada() {
        Date fechaSeleccionada = dchFechaSalida.getDate();
        if (fechaSeleccionada == null) {
            return null;
        }

        LocalDate fecha = fechaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();
        Date horaSeleccionada = (Date) spnHoraSalida.getValue();
        LocalTime hora = horaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault()).toLocalTime();
        return LocalDateTime.of(fecha, hora);
    }
    public void actualizarDatos() {
        cargarVuelos();
        cargarPilotos();
        cargarTablaVuelos();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        pnlInsertar = new javax.swing.JPanel();
        cmbAvion = new javax.swing.JComboBox<>();
        lblPaisDestino = new javax.swing.JLabel();
        txtPaisDestino = new javax.swing.JTextField();
        lblCiudadDestino = new javax.swing.JLabel();
        txtCiudadDestino = new javax.swing.JTextField();
        cmbPiloto = new javax.swing.JComboBox<>();
        lblPiloto = new javax.swing.JLabel();
        lblAvion = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        dchFechaSalida = new com.toedter.calendar.JDateChooser();
        lblHoraSalida = new javax.swing.JLabel();
        spnHoraSalida = new javax.swing.JSpinner();
        pnlBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelarVuelo = new javax.swing.JButton();
        btnFinalizarVuelo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Aerolinea", "Avion", "Piloto", "Pais Destino", "Ciudad Destino", "Fecha/Hora Salida", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVuelos);

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ASIGNAR VUELOS");

        cmbAvion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblPaisDestino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaisDestino.setText("Pais Destino:");

        lblCiudadDestino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCiudadDestino.setText("Ciudad Destino:");

        cmbPiloto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblPiloto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPiloto.setText("Piloto:");

        lblAvion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAvion.setText("Avion:");

        lblFechaSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaSalida.setText("Fecha de Salida:");

        lblHoraSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoraSalida.setText("Hora de Salida:");

        javax.swing.GroupLayout pnlInsertarLayout = new javax.swing.GroupLayout(pnlInsertar);
        pnlInsertar.setLayout(pnlInsertarLayout);
        pnlInsertarLayout.setHorizontalGroup(
            pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInsertarLayout.createSequentialGroup()
                        .addComponent(lblPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPiloto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInsertarLayout.createSequentialGroup()
                        .addComponent(lblAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAvion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInsertarLayout.createSequentialGroup()
                        .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCiudadDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPaisDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHoraSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPaisDestino)
                            .addComponent(txtCiudadDestino)
                            .addComponent(dchFechaSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(spnHoraSalida))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlInsertarLayout.setVerticalGroup(
            pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInsertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPiloto)
                    .addComponent(cmbPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaisDestino)
                    .addComponent(txtPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiudadDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dchFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaSalida))
                .addGap(18, 18, 18)
                .addGroup(pnlInsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHoraSalida)
                    .addComponent(spnHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("Registrar Nuevo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelarVuelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarVuelo.setText("Cancelar Vuelo");
        btnCancelarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVueloActionPerformed(evt);
            }
        });

        btnFinalizarVuelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFinalizarVuelo.setText("Finalizar Vuelo");
        btnFinalizarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVueloActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar Formulario");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(pnlInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVuelosMouseClicked
        int filaSeleccionada = tblVuelos.getSelectedRow();
        if (filaSeleccionada == -1) {
            return;
        }
        List<Vuelo> vuelos = vueloLogica.listarVuelos();
        vueloSeleccionado = vuelos.get(filaSeleccionada);

    }//GEN-LAST:event_tblVuelosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            Vuelo vuelo = new Vuelo();
            vuelo.setAvion((Avion) cmbAvion.getSelectedItem());
            vuelo.setPiloto((Piloto) cmbPiloto.getSelectedItem());
            vuelo.setPaisDestino(txtPaisDestino.getText());
            vuelo.setCiudadDestino(txtCiudadDestino.getText());
            vuelo.setFechaHoraSalida(obtenerFechaHoraSeleccionada());
            vuelo.setEstado("Programado");

            vueloLogica.registrarVuelo(vuelo);
            JOptionPane.showMessageDialog(this, "Vuelo registrado con exito. ");
            limpiarFormulario();
            cargarTablaVuelos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVueloActionPerformed
        if (vueloSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vuelo de la tabla primero. ",
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            vueloLogica.cancelarVuelo(vueloSeleccionado.getIdVuelo());
            JOptionPane.showMessageDialog(this, "Vuelo cancelado. ");
            vueloSeleccionado = null;
            tblVuelos.clearSelection();
            cargarTablaVuelos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarVueloActionPerformed

    private void btnFinalizarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVueloActionPerformed
        if (vueloSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un vuelo de la tabla. ",
                "Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            vueloLogica.finalizarVuelo(vueloSeleccionado.getIdVuelo());
            JOptionPane.showMessageDialog(this, "Vuelo finalizado. ");
            vueloSeleccionado = null;
            tblVuelos.clearSelection();
            cargarTablaVuelos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFinalizarVueloActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
        vueloSeleccionado = null;
        tblVuelos.clearSelection();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarVuelo;
    private javax.swing.JButton btnFinalizarVuelo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<Avion> cmbAvion;
    private javax.swing.JComboBox<Piloto> cmbPiloto;
    private com.toedter.calendar.JDateChooser dchFechaSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvion;
    private javax.swing.JLabel lblCiudadDestino;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblPaisDestino;
    private javax.swing.JLabel lblPiloto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInsertar;
    private javax.swing.JPanel pnlListar;
    private javax.swing.JSpinner spnHoraSalida;
    private javax.swing.JTable tblVuelos;
    private javax.swing.JTextField txtCiudadDestino;
    private javax.swing.JTextField txtPaisDestino;
    // End of variables declaration//GEN-END:variables
}
